import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Lightbulb, 
  TrendingDown, 
  TrendingUp, 
  Info, 
  ArrowRight,
  Sparkles,
  ChevronRight
} from 'lucide-react';

export interface InsightAction {
  label: string;
  onClick: () => void;
  primary?: boolean;
}

export interface SmartInsightsCardProps {
  /** The main title of the insight */
  title: string;
  /** Detailed summary of the insight generated by AI */
  summary: string;
  /** The type of insight to determine color and icon */
  type?: 'positive' | 'negative' | 'neutral' | 'alert';
  /** Array of actionable buttons */
  actions?: InsightAction[];
  /** Detailed data shown when expanding */
  details?: React.ReactNode;
  /** Custom icon to override default based on type */
  icon?: React.ReactNode;
}

const typeMap = {
  positive: {
    icon: TrendingUp,
    colors: 'bg-green-50/50 border-green-100 dark:bg-green-900 dark:border-green-800 dark:text-green-50',
    iconColors: 'text-green-600 bg-green-100 dark:text-green-400 dark:bg-green-900/50',
  },
  negative: {
    icon: TrendingDown,
    colors: 'bg-red-50/50 border-red-100 dark:bg-red-900 dark:border-red-800 dark:text-red-50',
    iconColors: 'text-red-600 bg-red-100 dark:text-red-400 dark:bg-red-900/50',
  },
  alert: {
    icon: Info,
    colors: 'bg-amber-50/50 border-amber-100 dark:bg-amber-900 dark:border-amber-800 dark:text-amber-50',
    iconColors: 'text-amber-600 bg-amber-100 dark:text-amber-400 dark:bg-amber-900/50',
  },
  neutral: {
    icon: Lightbulb,
    colors: 'bg-blue-50/50 border-blue-100 dark:bg-blue-900 dark:border-blue-800 dark:text-blue-50',
    iconColors: 'text-blue-600 bg-blue-100 dark:text-blue-400 dark:bg-blue-900/50',
  },
};

export const SmartInsightsCard: React.FC<SmartInsightsCardProps> = ({
  title,
  summary,
  type = 'neutral',
  actions = [],
  details,
  icon,
}) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const TypeIcon = typeMap[type].icon;
  const config = typeMap[type];

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`relative overflow-hidden rounded-2xl border p-5 transition-all ${config.colors} backdrop-blur-sm`}
    >
      <div className="absolute top-0 right-0 p-4 opacity-10">
        <Sparkles size={64} className="text-current" />
      </div>

      <div className="relative z-10">
        <div className="flex items-start gap-4">
          <div className={`p-2.5 rounded-xl ${config.iconColors} shrink-0`}>
            {icon || <TypeIcon size={20} />}
          </div>
          <div className="flex-1 min-w-0">
            <h4 className="text-base font-semibold text-text-primary mb-1">
              {title}
            </h4>
            <p className="text-sm text-gray-600 dark:text-gray-200 leading-relaxed">
              {summary}
            </p>
          </div>
        </div>

        {details && (
          <AnimatePresence>
            {isExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0, marginTop: 0 }}
                animate={{ height: 'auto', opacity: 1, marginTop: 16 }}
                exit={{ height: 0, opacity: 0, marginTop: 0 }}
                className="overflow-hidden"
              >
                <div className="pt-4 border-t border-gray-200/50 dark:border-gray-700/50">
                  {details}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        )}

        <div className="mt-5 flex items-center gap-3">
          {actions.map((action, idx) => (
            <button
              key={idx}
              onClick={action.onClick}
              className={`text-sm font-medium px-4 py-2 rounded-lg transition-colors flex items-center gap-2 ${
                action.primary
                  ? 'bg-gray-900 text-white hover:bg-gray-800 dark:bg-white dark:text-gray-900 dark:hover:bg-gray-100'
                  : 'bg-white/50 dark:bg-gray-800 text-gray-700 hover:bg-surface-primary dark:text-gray-200 dark:hover:bg-gray-700 shadow-sm border border-gray-200/50 dark:border-gray-700/50'
              }`}
            >
              {action.label}
              {action.primary && <ArrowRight size={14} />}
            </button>
          ))}
          
          {details && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="ml-auto flex items-center gap-1 text-sm font-medium text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors"
            >
              {isExpanded ? 'Ver menos' : 'Deep dive'}
              <motion.div animate={{ rotate: isExpanded ? -90 : 0 }}>
                <ChevronRight size={16} />
              </motion.div>
            </button>
          )}
        </div>
      </div>
    </motion.div>
  );
};
