interface InsightAction {
  label: string;
  onClick: () => void;
  primary?: boolean;
}


interface SmartInsightsCardProps {
  /** The main title of the insight */
  title: string;
  /** Detailed summary of the insight generated by AI */
  summary: string;
  /** The type of insight to determine color and icon */
  type?: 'positive' | 'negative' | 'neutral' | 'alert';
  /** Array of actionable buttons */
  actions?: InsightAction[];
  /** Detailed data shown when expanding */
  details?: React.ReactNode;
  /** Custom icon to override default based on type */
  icon?: React.ReactNode;
}
