import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Trophy, Star, Shield, Gift, ChevronRight, Lock, TrendingUp, Plane } from 'lucide-react';

export interface GamifiedRewardTierProps {
  userName?: string;
  points?: number;
  currentTier?: 'Bronze' | 'Silver' | 'Gold' | 'Platinum';
}

export const GamifiedRewardTier: React.FC<GamifiedRewardTierProps> = ({
  userName = "Alex",
  points = 2450,
  currentTier = "Silver"
}) => {
  const tiers = {
    Bronze: { color: 'from-amber-700 to-amber-900', light: 'text-amber-700', next: 'Silver', nextPoints: 1000, icon: Shield },
    Silver: { color: 'from-gray-300 to-gray-500', light: 'text-text-tertiary', next: 'Gold', nextPoints: 5000, icon: Star },
    Gold: { color: 'from-yellow-400 to-yellow-600', light: 'text-yellow-500', next: 'Platinum', nextPoints: 15000, icon: Trophy },
    Platinum: { color: 'from-blue-200 via-purple-300 to-blue-400', light: 'text-purple-400', next: null, nextPoints: 0, icon: Gift }
  };

  const tier = tiers[currentTier];
  const Icon = tier.icon;
  
  // Calculate progress
  const prevTierPoints = currentTier === 'Bronze' ? 0 : 
                         currentTier === 'Silver' ? tiers.Bronze.nextPoints : 
                         currentTier === 'Gold' ? tiers.Silver.nextPoints : tiers.Gold.nextPoints;
                         
  const pointsInCurrentLevel = points - prevTierPoints;
  const pointsNeededForNext = (tier.nextPoints - prevTierPoints);
  const progress = tier.next ? Math.min(100, Math.max(0, (pointsInCurrentLevel / pointsNeededForNext) * 100)) : 100;

  return (
    <div className="bg-surface-primary rounded-3xl border border-border-primary shadow-sm overflow-hidden">
      
      {/* Premium Header Header */}
      <div className="relative p-6 overflow-hidden">
        {/* Dynamic Background generated by current tier gradients */}
        <div className={`absolute inset-0 bg-gradient-to-br ${tier.color} opacity-10`} />
        
        <div className="relative z-10 flex justify-between items-start mb-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wider text-text-tertiary mb-1">
              Programa de Recompensas
            </p>
            <h2 className="text-xl font-bold text-text-primary flex items-center gap-2">
              Nivel {currentTier}
              <div className={`p-1 rounded-full bg-gradient-to-br ${tier.color} shadow-sm`}>
                <Icon size={14} className="text-white drop-shadow-sm" />
              </div>
            </h2>
          </div>
          
          <div className="text-right">
            <h3 className="text-2xl font-black text-text-primary tracking-tight">
              {points.toLocaleString()}
            </h3>
            <p className="text-xs font-medium text-text-tertiary uppercase">
              Puntos Vida
            </p>
          </div>
        </div>

        {/* Level Progress */}
        {tier.next && (
          <div className="relative mb-2">
            <div className="flex justify-between text-xs font-bold mb-2">
              <span className={`uppercase tracking-wider ${tier.light}`}>{currentTier}</span>
              <span className="text-text-tertiary uppercase tracking-wider">{tier.next}</span>
            </div>
            
            <div className="h-3 w-full bg-background-secondary rounded-full overflow-hidden shadow-inner">
              <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${progress}%` }}
                transition={{ duration: 1, ease: 'easeOut', delay: 0.2 }}
                className={`h-full rounded-full bg-gradient-to-r ${tier.color} relative`}
              >
                <div className="absolute inset-0 bg-white/20 w-full animate-[shimmer_2s_infinite] translate-x-full" style={{
                  backgroundImage: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.4), transparent)'
                }} />
              </motion.div>
            </div>
            
            <p className="text-center text-xs text-text-tertiary font-medium mt-3">
              Faltan <span className="font-bold text-text-primary">{(tier.nextPoints - points).toLocaleString()} puntos</span> para ascender
            </p>
          </div>
        )}
      </div>

      {/* Perks List */}
      <div className="bg-background-secondary p-6 border-t border-border-primary">
        <h4 className="text-sm font-semibold text-text-primary mb-4">
          Tus Beneficios Activos
        </h4>
        
        <div className="space-y-3">
          <div className="flex items-center gap-3 p-3 bg-surface-primary rounded-xl border border-border-primary shadow-sm">
            <div className="p-2 bg-green-50 dark:bg-green-900 text-green-600 dark:text-green-400 rounded-lg">
              <TrendingUp size={16} />
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold text-text-primary">Cashback 2%</p>
              <p className="text-xs text-text-tertiary">En todas tus compras</p>
            </div>
            <CheckBadge />
          </div>
          
          <div className="flex items-center gap-3 p-3 bg-surface-primary rounded-xl border border-border-primary shadow-sm relative overflow-hidden group">
            <div className="absolute inset-0 bg-gradient-to-r from-yellow-400/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
            <div className="p-2 bg-yellow-50 dark:bg-yellow-900 text-yellow-600 dark:text-yellow-400 rounded-lg relative z-10">
              <Gift size={16} />
            </div>
            <div className="flex-1 relative z-10">
              <p className="text-sm font-semibold text-text-primary cursor-pointer flex items-center gap-1 group-hover:text-yellow-600 dark:group-hover:text-yellow-400 transition-colors">
                Regalo de Cumpleaños <ChevronRight size={14} />
              </p>
              <p className="text-xs text-text-tertiary">Disponible tu mes</p>
            </div>
            <CheckBadge className="relative z-10" />
          </div>

          {tier.next && (
            <div className="flex items-center gap-3 p-3 border border-dashed border-border-primary rounded-xl opacity-60 grayscale hover:grayscale-0 transition-all cursor-not-allowed">
              <div className="p-2 bg-background-secondary text-text-tertiary rounded-lg">
                <Plane size={16} />
              </div>
              <div className="flex-1">
                <p className="text-sm font-semibold flex items-center gap-2">
                  Acceso VIP Aeropuertos <Lock size={12} className="text-yellow-500" />
                </p>
                <p className="text-xs text-text-tertiary">Disponible en Nivel {tier.next}</p>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

const CheckBadge = ({ className = "" }) => (
  <div className={`w-5 h-5 rounded-full bg-blue-500 text-white flex items-center justify-center shrink-0 shadow-sm ${className}`}>
    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12"></polyline>
    </svg>
  </div>
);
